import gradio as gr
import subprocess
import re
import glob
import threading
import os
import shutil
import sys
import time
import requests
import json
import urllib.parse
from datetime import date
import platform
import tarfile
import tempfile

# 全局标志，标记后端服务是否已启动
backend_ready = False
backend_failed = False
BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL", "http://127.0.0.1:13579").rstrip("/")
NODE_MIN_MAJOR = int(os.getenv("NODE_MIN_MAJOR", "18"))

# 设置环境变量，强制不走代理
os.environ["NO_PROXY"] = "localhost,127.0.0.1"


def backend_url(path):
    if not path.startswith("/"):
        path = "/" + path
    return f"{BACKEND_BASE_URL}{path}"


def backend_healthcheck(base_url, timeout=3):
    try:
        response = requests.get(f"{base_url}/api/ip", timeout=timeout)
        return response.status_code == 200
    except Exception:
        return False

def amap_request(url, params, timeout=10):
    try:
        response = requests.get(url, params=params, timeout=timeout)
        if response.status_code != 200:
            return None
        return response.json()
    except Exception:
        return None


def amap_place_around(location, types_code, radius=5000, limit=6):
    api_key = os.getenv("AMAP_API_KEY", "").strip()
    if not api_key:
        return []
    params = {
        "key": api_key,
        "location": location,
        "types": types_code,
        "radius": radius,
        "sortrule": "distance",
        "offset": limit,
        "page": 1,
        "extensions": "all",
    }
    data = amap_request("https://restapi.amap.com/v3/place/around", params)
    if not data or data.get("status") != "1":
        return []
    return data.get("pois", []) or []


def normalize_amap_poi(poi):
    name = poi.get("name")
    if not name:
        return None
    address = poi.get("address") or ""
    distance = poi.get("distance") or ""
    category = poi.get("type") or ""
    biz = poi.get("biz_ext") or {}
    rec = {
        "name": name,
        "address": address,
        "distance": distance,
        "type": category,
    }
    rating = biz.get("rating")
    cost = biz.get("cost")
    if rating or cost:
        rec["business"] = {}
        if rating:
            rec["business"]["rating"] = rating
        if cost:
            rec["business"]["cost"] = cost
    return rec


def fallback_recommendation(preference, types_list, origin, latitude, longitude):
    location = f"{longitude},{latitude}"
    results = []
    seen = set()
    for t in types_list:
        pois = amap_place_around(location, t, radius=5000, limit=6)
        for poi in pois:
            rec = normalize_amap_poi(poi)
            if not rec:
                continue
            key = rec.get("name")
            if key in seen:
                continue
            seen.add(key)
            results.append(rec)
            if len(results) >= 8:
                break
        if len(results) >= 8:
            break

    if not results:
        results = [
            {
                "name": "Team Building Venue",
                "address": origin or "",
                "distance": "",
                "type": "",
            }
        ]

    return {
        "recommendations": results,
        "reason": "Generated by Python fallback (no Node.js backend).",
    }


def parse_time_to_minutes(value, default_minutes):
    try:
        parts = value.split(":")
        if len(parts) != 2:
            return default_minutes
        hour = int(parts[0])
        minute = int(parts[1])
        return hour * 60 + minute
    except Exception:
        return default_minutes


def minutes_to_time(value):
    value = max(0, int(value))
    hour = value // 60
    minute = value % 60
    return f"{hour:02d}:{minute:02d}"


def fallback_teamplan(plan_name, people_count, budget_range, start_time, end_time, start_location, latitude, longitude):
    per_capita = 0
    if isinstance(budget_range, (list, tuple)) and budget_range:
        if len(budget_range) == 1:
            per_capita = float(budget_range[0])
        else:
            per_capita = sum(budget_range) / len(budget_range)
    elif isinstance(budget_range, (int, float)):
        per_capita = float(budget_range)

    location = f"{longitude},{latitude}"
    activity_pois = amap_place_around(location, "080000", radius=8000, limit=4)
    food_pois = amap_place_around(location, "050000", radius=8000, limit=4)

    activities = []
    if activity_pois:
        rec = normalize_amap_poi(activity_pois[0])
        if rec:
            activities.append({
                "name": rec.get("name"),
                "type": "activity",
                "address": rec.get("address", ""),
                "description": "Nearby activity venue",
            })
    if food_pois:
        rec = normalize_amap_poi(food_pois[0])
        if rec:
            activities.append({
                "name": rec.get("name"),
                "type": "food",
                "address": rec.get("address", ""),
                "description": "Nearby dining option",
            })
    if len(activities) < 2 and activity_pois:
        rec = normalize_amap_poi(activity_pois[-1])
        if rec:
            activities.append({
                "name": rec.get("name"),
                "type": "activity",
                "address": rec.get("address", ""),
                "description": "Team activity",
            })

    if not activities:
        activities = [
            {
                "name": "Team Building",
                "type": "activity",
                "address": start_location or "",
                "description": "Fallback plan",
            }
        ]

    start_min = parse_time_to_minutes(start_time or "09:00", 9 * 60)
    end_min = parse_time_to_minutes(end_time or "18:00", 18 * 60)
    if end_min <= start_min:
        end_min = start_min + 8 * 60

    slot = max(60, (end_min - start_min) // max(len(activities), 1))
    for idx, act in enumerate(activities):
        s = start_min + idx * slot
        e = min(end_min, s + slot)
        act["timeRange"] = {"start": minutes_to_time(s), "end": minutes_to_time(e)}

    return {
        "title": plan_name or "Team Building Plan",
        "budgetInfo": {
            "perCapitaCost": int(per_capita) if per_capita else None,
            "totalBudget": int(per_capita * people_count) if per_capita else None,
            "activityCount": len(activities),
        },
        "activities": activities,
        "isMultiDay": False,
    }


def format_recommendation_result(result_data):
    """
    美化推荐结果的显示格式
    """
    if isinstance(result_data, str):
        # 如果是字符串，尝试解析为JSON
        try:
            result_data = json.loads(result_data)
        except:
            return result_data
    
    if isinstance(result_data, dict):
        formatted = "# 🎯 推荐结果\n\n"
        
        # 如果有POI推荐列表
        if "pois" in result_data or "recommendations" in result_data:
            pois = result_data.get("pois") or result_data.get("recommendations", [])
            
            if pois:
                formatted += "## 📍 推荐地点\n\n"
                for idx, poi in enumerate(pois, 1):
                    formatted += f"### {idx}. {poi.get('name', '未知地点')}\n\n"
                    
                    # 基本信息
                    if poi.get('address'):
                        formatted += f"📍 **地址**: {poi['address']}\n\n"
                    
                    if poi.get('distance'):
                        formatted += f"🚗 **距离**: {poi['distance']}\n\n"
                    
                    if poi.get('duration'):
                        formatted += f"⏱️ **通勤时间**: {poi['duration']}\n\n"
                    
                    # 评分和价格 - 从 business 对象中读取
                    if poi.get('business'):
                        business = poi['business']
                        if business.get('rating'):
                            rating = business['rating']
                            try:
                                stars = "⭐" * int(float(rating))
                                formatted += f"⭐ **评分**: {rating} {stars}\n\n"
                            except:
                                formatted += f"⭐ **评分**: {rating}\n\n"
                        if business.get('cost'):
                            cost = str(business['cost']).rstrip('0').rstrip('.') if '.' in str(business['cost']) else str(business['cost'])
                            formatted += f"💰 **人均消费**: ¥{cost}\n\n"
                    elif poi.get('rating'):
                        try:
                            stars = "⭐" * int(float(poi['rating']))
                            formatted += f"⭐ **评分**: {poi['rating']} {stars}\n\n"
                        except:
                            formatted += f"⭐ **评分**: {poi['rating']}\n\n"
                    
                    if not poi.get('business') and (poi.get('price') or poi.get('avgPrice')):
                        price = poi.get('price') or poi.get('avgPrice')
                        formatted += f"💰 **人均消费**: ¥{price}\n\n"
                    
                    # 类型和标签
                    if poi.get('type') or poi.get('category'):
                        category = poi.get('type') or poi.get('category')
                        formatted += f"🏷️ **类型**: {category}\n\n"
                    
                    if poi.get('tags'):
                        tags = poi['tags']
                        if isinstance(tags, list):
                            tags_str = " · ".join(tags)
                        else:
                            tags_str = str(tags)
                        formatted += f"🔖 **标签**: {tags_str}\n\n"
                    
                    # 描述
                    if poi.get('description'):
                        formatted += f"📝 **简介**: {poi['description']}\n\n"
                    
                    # 联系方式
                    if poi.get('phone') or poi.get('tel'):
                        phone = poi.get('phone') or poi.get('tel')
                        formatted += f"📞 **电话**: {phone}\n\n"
                    
                    # 营业时间
                    if poi.get('openTime') or poi.get('businessHours'):
                        hours = poi.get('openTime') or poi.get('businessHours')
                        formatted += f"🕐 **营业时间**: {hours}\n\n"
                    
                    formatted += "---\n\n"
            else:
                formatted += "暂无推荐地点\n\n"
        
        # 如果有推荐理由
        if "reason" in result_data or "recommendation_reason" in result_data:
            reason = result_data.get("reason") or result_data.get("recommendation_reason")
            formatted += f"## 💡 推荐理由\n\n{reason}\n\n"
        
        # 如果有总结
        if "summary" in result_data:
            formatted += f"## 📊 推荐总结\n\n{result_data['summary']}\n\n"
        
        # 如果有路线规划
        if "route" in result_data or "itinerary" in result_data:
            route = result_data.get("route") or result_data.get("itinerary")
            formatted += f"## 🗺️ 行程规划\n\n{route}\n\n"
        
        # 其他信息
        other_keys = set(result_data.keys()) - {
            'pois', 'recommendations', 'reason', 'recommendation_reason', 
            'summary', 'route', 'itinerary'
        }
        
        if other_keys:
            formatted += "## ℹ️ 其他信息\n\n"
            for key in other_keys:
                value = result_data[key]
                formatted += f"**{key}**: {value}\n\n"
        
        return formatted
    
    # 如果是列表
    elif isinstance(result_data, list):
        formatted = "# 🎯 推荐结果\n\n"
        for idx, item in enumerate(result_data, 1):
            if isinstance(item, dict):
                formatted += f"## {idx}. {item.get('name', f'推荐 {idx}')}\n\n"
                formatted += format_dict_item(item)
                formatted += "\n---\n\n"
            else:
                formatted += f"{idx}. {str(item)}\n\n"
        return formatted
    
    # 其他情况，返回原始格式
    return str(result_data)


def format_dict_item(item_dict):
    """格式化字典项"""
    formatted = ""
    
    # 图标映射
    icon_map = {
        'name': '📍',
        'address': '🏠',
        'distance': '📏',
        'duration': '⏱️',
        'rating': '⭐',
        'price': '💰',
        'avgPrice': '💰',
        'type': '🏷️',
        'category': '🏷️',
        'tags': '🔖',
        'description': '📝',
        'phone': '📞',
        'tel': '📞',
        'openTime': '🕐',
        'businessHours': '🕐'
    }
    
    for key, value in item_dict.items():
        if key == 'name':
            continue  # name 已经在标题中显示
        
        icon = icon_map.get(key, '•')
        
        if key == 'rating' and value:
            stars = "⭐" * int(float(value))
            formatted += f"{icon} **{key}**: {value} {stars}\n\n"
        elif key == 'tags' and isinstance(value, list):
            tags_str = " · ".join(str(t) for t in value)
            formatted += f"{icon} **{key}**: {tags_str}\n\n"
        elif value:
            formatted += f"{icon} **{key}**: {value}\n\n"
    
    return formatted




def _rewrite_apt_sources(mirror_url=None):
    if not sys.platform.startswith("linux"):
        return False
    mirror = (mirror_url or os.getenv("APT_MIRROR", "")).strip()
    if mirror:
        mirror_base = mirror
        security_base = mirror
    else:
        mirror_base = "http://archive.ubuntu.com/ubuntu"
        security_base = "http://security.ubuntu.com/ubuntu"

    paths = ["/etc/apt/sources.list"]
    paths.extend(glob.glob("/etc/apt/sources.list.d/*.list"))
    changed = False
    for path in paths:
        try:
            if not os.path.exists(path):
                continue
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
            new = content
            for old in (
                "http://mirrors.aliyun.com/ubuntu",
                "https://mirrors.aliyun.com/ubuntu",
                "http://archive.ubuntu.com/ubuntu",
                "https://archive.ubuntu.com/ubuntu",
            ):
                new = new.replace(old, mirror_base)
            for old in (
                "http://security.ubuntu.com/ubuntu",
                "https://security.ubuntu.com/ubuntu",
            ):
                new = new.replace(old, security_base)
            if new != content:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(new)
                changed = True
        except Exception as e:
            print(f"Warning: failed to rewrite apt sources {path}: {e}")
    return changed


def _run_apt_get(args, env):
    return subprocess.run(
        ["apt-get"] + args,
        check=True,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def _parse_node_major(version_output):
    if not version_output:
        return None
    match = re.search(r"v?(\d+)\.", version_output.strip())
    if not match:
        return None
    try:
        return int(match.group(1))
    except Exception:
        return None

def _node_version_ok(result, min_major):
    if result is None or result.returncode != 0:
        return False
    major = _parse_node_major(result.stdout)
    if major is None:
        return False
    if major < min_major:
        print(f"Warning: Node.js v{major} detected, but >= {min_major} is required.")
        return False
    return True

def _detect_node_dist():
    machine = platform.machine().lower()
    if machine in ("x86_64", "amd64"):
        return "linux-x64"
    if machine in ("aarch64", "arm64"):
        return "linux-arm64"
    if machine.startswith("armv7"):
        return "linux-armv7l"
    if machine.startswith("armv6"):
        return "linux-armv6l"
    return None

def _get_node_version(min_major):
    env_ver = os.getenv("NODE_VERSION", "").strip()
    if env_ver:
        return env_ver.lstrip("v")
    index_urls = []
    env_index = os.getenv("NODE_INDEX_URL", "").strip()
    if env_index:
        index_urls.append(env_index)
    index_urls += [
        "https://nodejs.org/dist/index.json",
        "https://npmmirror.com/mirrors/node/index.json",
    ]
    for url in index_urls:
        try:
            resp = requests.get(url, timeout=10)
            if resp.status_code != 200:
                continue
            data = resp.json()
            for entry in data:
                ver = (entry.get("version") or "").lstrip("v")
                if ver.split(".")[0] == str(min_major):
                    return ver
        except Exception:
            continue
    fallback = {
        18: "18.20.4",
        20: "20.11.1",
        22: "22.3.0",
    }
    return fallback.get(min_major, f"{min_major}.20.0")

def _download_file(url, dest, timeout=30):
    resp = None
    try:
        resp = requests.get(url, stream=True, timeout=timeout)
        if resp.status_code != 200:
            return False
        with open(dest, "wb") as f:
            for chunk in resp.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)
        return True
    except Exception as e:
        print(f"Warning: download failed: {e}")
        return False
    finally:
        if resp is not None:
            try:
                resp.close()
            except Exception:
                pass

def _install_node_from_tarball(env, min_major):
    dist = _detect_node_dist()
    if not dist:
        print("Warning: unsupported architecture for Node.js binary")
        return False
    version = _get_node_version(min_major)
    if not version:
        print("Warning: unable to determine Node.js version")
        return False
    base_candidates = []
    env_base = os.getenv("NODE_DIST_BASE", "").strip()
    if env_base:
        base_candidates.append(env_base.rstrip("/"))
    base_candidates += [
        "https://nodejs.org/dist",
        "https://npmmirror.com/mirrors/node",
    ]
    cache_root = os.path.join(os.path.dirname(__file__), ".node")
    os.makedirs(cache_root, exist_ok=True)
    target_dir = os.path.join(cache_root, f"node-v{version}-{dist}")
    node_bin = os.path.join(target_dir, "bin", "node")
    if os.path.exists(node_bin):
        env["PATH"] = f"{os.path.join(target_dir, 'bin')}{os.pathsep}{env.get('PATH', '')}"
        env["NODE_HOME"] = target_dir
        return True
    tar_name = f"node-v{version}-{dist}.tar.xz"
    for base in base_candidates:
        url = f"{base}/v{version}/{tar_name}"
        print(f"Downloading Node.js from {url}...")
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                tar_path = os.path.join(tmpdir, tar_name)
                if not _download_file(url, tar_path):
                    continue
                try:
                    with tarfile.open(tar_path, "r:xz") as tf:
                        tf.extractall(path=cache_root)
                except Exception as e:
                    print(f"Warning: failed to extract Node.js tarball: {e}")
                    continue
        except Exception as e:
            print(f"Warning: download/extract failed: {e}")
            continue
        if os.path.exists(node_bin):
            env["PATH"] = f"{os.path.join(target_dir, 'bin')}{os.pathsep}{env.get('PATH', '')}"
            env["NODE_HOME"] = target_dir
            return True
    return False

def _install_node(env, min_major):
    if not sys.platform.startswith("linux"):
        return False
    env.setdefault("DEBIAN_FRONTEND", "noninteractive")
    force_tarball = os.getenv("FORCE_NODE_TARBALL", "").strip().lower() in ("1", "true", "yes", "y")
    skip_apt = os.getenv("SKIP_APT", "").strip().lower() in ("1", "true", "yes", "y")
    if force_tarball or skip_apt:
        print("Skipping apt-get; forcing Node.js tarball install.")
        return _install_node_from_tarball(env, min_major)
    if shutil.which("apt-get"):
        try:
            try:
                _run_apt_get(["update"], env)
            except subprocess.CalledProcessError as e:
                err_tail = ""
                if getattr(e, "stderr", None):
                    err_tail = e.stderr.strip().splitlines()[-1]
                if err_tail:
                    print(f"Warning: apt-get update failed: {err_tail}")
                else:
                    print(f"Warning: apt-get update failed: {e}")
                if _rewrite_apt_sources():
                    print("Retrying apt-get update after rewriting sources...")
                    _run_apt_get(["update"], env)
                else:
                    raise

            try:
                _run_apt_get(["install", "-y", "ca-certificates", "curl", "gnupg"], env)
            except subprocess.CalledProcessError as e:
                err_tail = ""
                if getattr(e, "stderr", None):
                    err_tail = e.stderr.strip().splitlines()[-1]
                if err_tail:
                    print(f"Warning: apt-get install prereqs failed: {err_tail}")
                else:
                    print(f"Warning: apt-get install prereqs failed: {e}")

            if shutil.which("curl"):
                setup_url = f"https://deb.nodesource.com/setup_{min_major}.x"
                try:
                    subprocess.run(
                        ["bash", "-c", f"curl -fsSL {setup_url} | bash -"],
                        check=True,
                        env=env,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True,
                    )
                except subprocess.CalledProcessError as e:
                    err_tail = ""
                    if getattr(e, "stderr", None):
                        err_tail = e.stderr.strip().splitlines()[-1]
                    if err_tail:
                        print(f"Warning: NodeSource setup failed: {err_tail}")
                    else:
                        print(f"Warning: NodeSource setup failed: {e}")

            _run_apt_get(["install", "-y", "nodejs", "npm"], env)
            return True
        except subprocess.CalledProcessError as e:
            err_tail = ""
            if getattr(e, "stderr", None):
                err_tail = e.stderr.strip().splitlines()[-1]
            if err_tail:
                print(f"Warning: apt-get install failed: {err_tail}")
            else:
                print(f"Warning: apt-get install failed: {e}")
        except Exception as e:
            print(f"Warning: apt-get install failed: {e}")
    print("Falling back to Node.js binary tarball install...")
    return _install_node_from_tarball(env, min_major)


def _run_npm(args, env, cwd):
    return subprocess.run(
        ["npm"] + args,
        check=True,
        env=env,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def _ensure_node_modules(backend_dir, env):
    if os.getenv("SKIP_NPM_INSTALL", "").strip().lower() in ("1", "true", "yes", "y"):
        return True

    package_json = os.path.join(backend_dir, "package.json")
    if not os.path.exists(package_json):
        print("Warning: package.json not found; skipping npm install")
        return True

    node_modules = os.path.join(backend_dir, "node_modules")
    express_dir = os.path.join(node_modules, "express")
    if os.path.exists(express_dir):
        return True

    npm_registry = os.getenv("NPM_REGISTRY", "").strip()
    if not npm_registry:
        npm_registry = os.getenv("NPM_CONFIG_REGISTRY", "").strip()
    if not npm_registry:
        npm_registry = "https://registry.npmmirror.com"
    env["NPM_CONFIG_REGISTRY"] = npm_registry

    lock_path = os.path.join(backend_dir, "package-lock.json")
    cmd = ["ci", "--omit=dev", "--no-audit", "--no-fund"] if os.path.exists(lock_path) else ["install", "--omit=dev", "--no-audit", "--no-fund"]
    try:
        print(f"Installing backend dependencies via npm ({' '.join(cmd)})...")
        _run_npm(cmd, env, backend_dir)
        return True
    except subprocess.CalledProcessError as e:
        err_tail = ""
        if getattr(e, "stderr", None):
            err_tail = e.stderr.strip().splitlines()[-1] if e.stderr.strip() else ""
        if err_tail:
            print(f"Warning: npm ci failed: {err_tail}")
        else:
            print(f"Warning: npm ci failed: {e}")
        try:
            print("Retrying npm install...")
            _run_npm(["install", "--omit=dev", "--no-audit", "--no-fund"], env, backend_dir)
            return True
        except Exception as e2:
            print(f"Warning: npm install failed: {e2}")
            return False
    except FileNotFoundError:
        print("Warning: npm not found in PATH")
        return False
def start_backend_service():
    """启动 Node.js 后端服务"""
    global backend_ready, backend_failed
    try:
        # 设置环境变量
        env = os.environ.copy()
        # 为后端服务指定一个不同的端口，避免与Gradio冲突
        env["PORT"] = "13579"  # 改为13579端口，避开8080
        env["HOST"] = "127.0.0.1" # 只监听本地回环，避免被外部代理拦截

        
        # 设置数据库环境变量为默认值（避免数据库连接错误）
        env["DB_HOST"] = env.get("DB_HOST", "127.0.0.1")
        env["DB_USER"] = env.get("DB_USER", "root")
        env["DB_PORT"] = env.get("DB_PORT", "3306")
        env["DB_PASSWORD"] = env.get("DB_PASSWORD", "")
        env["DB_NAME"] = env.get("DB_NAME", "hipong")
        
        # 确保API密钥环境变量被传递
        env["DEEPSEEK_API_KEY"] = os.getenv("DEEPSEEK_API_KEY", "")
        env["AMAP_API_KEY"] = os.getenv("AMAP_API_KEY", "")
        env["DOUYIN_APPID"] = os.getenv("DOUYIN_APPID", "")
        env["DOUYIN_SECRET"] = os.getenv("DOUYIN_SECRET", "")
        env["DOUYIN_SANDBOX"] = os.getenv("DOUYIN_SANDBOX", "true")
        
        # Ensure Node.js is available and meets minimum version.
        result = None
        try:
            result = subprocess.run(["node", "--version"], capture_output=True, text=True, timeout=10, env=env)
        except FileNotFoundError:
            result = None

        if not _node_version_ok(result, NODE_MIN_MAJOR):
            auto_install_raw = os.getenv("AUTO_INSTALL_NODE", "").strip().lower()
            auto_install = auto_install_raw not in ("0", "false", "no", "n")
            if not auto_install:
                print("Node.js not found; auto-install disabled by AUTO_INSTALL_NODE=0.")
                backend_failed = True
                return
            print("Node.js not found or too old. Attempting to install/upgrade...")
            if not _install_node(env, NODE_MIN_MAJOR):
                backend_failed = True
                return
            try:
                result = subprocess.run(["node", "--version"], capture_output=True, text=True, timeout=10, env=env)
            except FileNotFoundError:
                result = None
        if not _node_version_ok(result, NODE_MIN_MAJOR):
            print("Warning: Node.js is not available or version is too low")
            backend_failed = True  # ??True?????????
            return

        print(f"Starting HIPONG backend service with Node.js {result.stdout.strip()}")
        
        # 检查 server.js 是否存在（在容器中的正确路径）
        backend_dir = os.path.join(os.path.dirname(__file__), "backend")
        server_path = os.path.join(backend_dir, "server.js")
        
        print(f"Looking for server.js at: {server_path}")
        print(f"Backend directory exists: {os.path.exists(backend_dir)}")
        print(f"Server.js exists: {os.path.exists(server_path)}")
        
        if not os.path.exists(server_path):
            print(f"Warning: {server_path} not found")
            # 尝试列出 backend 目录下的文件
            if os.path.exists(backend_dir):
                files = os.listdir(backend_dir)
                print(f"Files in backend directory: {files}")
            else:
                print("Backend directory does not exist!")
            backend_failed = True  # 设为True以避免界面无限等待
            return

        if not _ensure_node_modules(backend_dir, env):
            backend_failed = True
            print("Backend dependencies install failed")
            return
            
        # 启动 Node.js 服务器
        process = subprocess.Popen(
            ["node", "server.js"],
            cwd=backend_dir,  # 在 backend 目录下运行
            env=env
        )
        
        # 等待一段时间让服务启动
        time.sleep(15)

        if backend_healthcheck(BACKEND_BASE_URL, timeout=3):
            backend_ready = True
            print("Backend service ready")
        else:
            backend_failed = True
            print("Backend service health check failed")
        
        # 等待进程结束（保持服务运行)
        process.wait()
        
    except subprocess.TimeoutExpired:
        print("Warning: Node.js version check timed out")
        backend_failed = True
    except FileNotFoundError:
        print("Warning: Node.js is not installed or not in PATH")
        backend_failed = True
    except Exception as e:
        print(f"Error starting Node.js backend: {e}")
        backend_failed = True

def launch_backend():
    """在后台线程中启动 Node.js 服务"""
    try:
        backend_thread = threading.Thread(target=start_backend_service, daemon=True)
        backend_thread.start()
        return backend_thread
    except Exception as e:
        print(f"Failed to launch backend: {e}")
        global backend_failed
        backend_failed = True
        return None

# 启动后端服务（在单独的线程中）
print("Launching backend service...")
backend_thread = launch_backend()

def get_public_routes():
    """
    尝试访问不需要认证的公共路由
    """
    print("尝试访问公共路由...")
    
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'User-Agent': 'Mozilla/5.0 (compatible; HIPONG App)',
        'Origin': 'http://127.0.0.1:13579',
        'Referer': 'http://127.0.0.1:13579/'
    }
    
    # 测试根路径
    try:
        response = requests.get(backend_url("/"), headers=headers, timeout=10)
        print(f"根路径访问状态: {response.status_code}")
        print(f"根路径响应内容: {response.text}")
    except Exception as e:
        print(f"根路径访问失败: {str(e)}")
    
    # 测试/api路径
    try:
        response = requests.get(backend_url("/api"), headers=headers, timeout=10)
        print(f"/api路径访问状态: {response.status_code}")
        print(f"/api路径响应内容: {response.text}")
    except Exception as e:
        print(f"/api路径访问失败: {str(e)}")

def get_location_coordinates(location_name):
    """
    根据地点名称获取经纬度坐标
    """
    api_key = os.getenv("AMAP_API_KEY", "c644dfe4025597410cbdf2b6de3bd8d2")
    encoded_location = urllib.parse.quote(location_name)
    url = f"https://restapi.amap.com/v3/geocode/geo?key={api_key}&address={encoded_location}"
    
    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            data = response.json()
            if data.get("status") == "1" and data.get("geocodes"):
                location = data["geocodes"][0]["location"]
                if location:
                    lng, lat = location.split(",")
                    return float(lat), float(lng)
    except Exception as e:
        print(f"获取坐标失败: {e}")
    
    # 如果获取失败，返回默认坐标（杭州）
    return 30.2741, 120.1551

def hipong_demo(preference, types, origin, people_count, budget, max_transit_time, *partner_locations):
    """
    HIPONG 地点推荐系统演示函数
    """
    print(f"接收到推荐请求: 活动偏好={preference}, 地点类型={types}, 出发地点={origin}, 参与人数={people_count}, 人均预算={budget}, 最大通勤时间={max_transit_time}")
    
    global backend_ready, backend_failed

    if backend_failed:
        # Use Python fallback when Node.js backend is unavailable (ModelScope space).
        latitude, longitude = get_location_coordinates(origin or "")
        TYPE_MAP = {
            "\u9910\u996e": "050000",
            "\u4f53\u80b2\u4f11\u95f2": "080000",
            "\u8d2d\u7269": "060000",
            "\u98ce\u666f\u540d\u80dc": "110000",
            "\u79d1\u6559\u6587\u5316": "140000",
        }
        types_list = [TYPE_MAP[t] for t in (types or []) if t in TYPE_MAP]
        if not types_list:
            types_list = ["050000", "080000"]
        fallback_result = fallback_recommendation(
            preference, types_list, origin, latitude, longitude
        )
        return format_recommendation_result(fallback_result)
    
    # 如果后端尚未准备好，给出提示
    if not backend_ready:
        return f"## ⏳ 系统状态\n\n系统已接收请求，后端服务正在启动中...\n\n### 📋 请求信息\n\n- **活动偏好**: {preference}\n- **地点类型**: {types}\n- **出发地点**: {origin}\n- **参与人数**: {people_count} 人\n- **人均预算**: ¥{budget}\n- **最大通勤时间**: {max_transit_time} 分钟\n\n请稍候..."
    
    # 获取实际的经纬度坐标
    latitude, longitude = get_location_coordinates(origin)
    print(f"获取到 {origin} 的坐标: ({latitude}, {longitude})")
    
    # 获取同行者位置信息
    partners = []
    for i in range(int(people_count) - 1):  # 减1是因为origin是第一个用户
        if i < len(partner_locations) and partner_locations[i]:
            partner_lat, partner_lng = get_location_coordinates(partner_locations[i])
            partners.append({
                "name": f"同行者{i+1}",
                "latitude": partner_lat,
                "longitude": partner_lng
            })
            print(f"获取到同行者{i+1} {partner_locations[i]} 的坐标: ({partner_lat}, {partner_lng})")
    
    # 将类型列表转换为后端所需的格式
    # 根据TYPE_MAP将中文类型转换为高德API所需的类型码
    TYPE_MAP = {
        "餐饮": "050000",
        "体育休闲": "080000",
        "购物": "060000",
        "风景名胜": "110000",
        "科教文化": "140000",
    }
    
    # 将中文类型转换为类型码
    types_list = [TYPE_MAP[t] for t in types if t in TYPE_MAP]
    if not types_list:
        types_list = ["050000", "080000"]  # 默认类型：餐饮和体育休闲
    
    # 先尝试访问公共路由，诊断认证问题
    get_public_routes()
    
    # 尝试调用后端服务 - 改为8080端口
    try:
        payload = {
            "preferenceText": preference,
            "origin": {
                "name": origin,
                "latitude": latitude,
                "longitude": longitude
            },
            "partners": partners,
            "types": types_list,
            "maxTransitTime": int(max_transit_time),
            "maxBudget": int(budget) if budget else None,
            "minBudget": None
        }
        
        print(f"发送请求到后端: {payload}")
        
        # 设置请求头
        headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'User-Agent': 'Mozilla/5.0 (compatible; HIPONG App)',
            'Origin': 'http://127.0.0.1:13579',
            'Referer': 'http://127.0.0.1:13579/'
        }
        
        # 首先尝试不带认证的请求
        print("尝试不带认证的请求...")
        response = requests.post(
            backend_url("/getInitialPoisByPrefs"),
            json=payload,
            headers=headers,
            timeout=30  # 增加超时时间
        )
        
        print(f"后端响应状态码: {response.status_code}")
        print(f"后端响应内容: {response.text}")
        
        if response.status_code == 200:
            result = response.json()
            print(f"后端响应数据: {result}")
            
            if result.get("success"):
                rec_id = result.get("recId")
                if rec_id:
                    # 开始轮询查询结果
                    polling_attempts = 30  # 最多重试30次
                    polling_interval = 5  # 每5秒查询一次
                    
                    print(f"获取到推荐任务ID: {rec_id}")
                    
                    for i in range(polling_attempts):
                        # 查询任务状态
                        status_response = requests.get(
                            backend_url(f"/recommendation-status/{rec_id}"),
                            headers=headers,
                            timeout=10
                        )
                        
                        print(f"轮询状态响应: {status_response.status_code}")
                        print(f"轮询状态内容: {status_response.text}")
                        
                        if status_response.status_code == 200:
                            status_result = status_response.json()
                            print(f"状态查询结果: {status_result}")
                            
                            if status_result.get("success"):
                                task_status = status_result.get("taskStatus", {})
                                
                                if task_status.get("ready"):
                                    if task_status.get("success"):
                                        final_result = task_status.get("data")
                                        print(f"成功获取推荐结果: {final_result}")
                                        # 使用美化函数格式化结果
                                        return format_recommendation_result(final_result)
                                    else:
                                        error_msg = task_status.get("error", "未知错误")
                                        print(f"推荐服务处理失败: {error_msg}")
                                        return f"## ❌ 推荐失败\n\n{error_msg}"
                                else:
                                    # 任务仍在处理中，更新状态信息
                                    remaining_time = (polling_attempts - i - 1) * polling_interval
                                    print(f"任务仍在处理中...剩余时间约 {remaining_time} 秒")
                                    # 继续轮询
                            else:
                                print("查询状态失败，尝试继续轮询...")
                        else:
                            print(f"状态查询失败，HTTP {status_response.status_code}")
                        
                        # 等待一段时间再查询
                        time.sleep(polling_interval)
                    
                    print("处理超时")
                    return f"## ⏱️ 处理超时\n\n### 📋 请求信息\n\n- **活动偏好**: {preference}\n- **出发地点**: {origin}\n- **参与人数**: {people_count} 人\n- **人均预算**: ¥{budget}\n- **最大通勤时间**: {max_transit_time} 分钟\n\n处理时间过长，请稍后再试"
                else:
                    print("后端服务响应: 未能获取任务ID")
                    return f"## ❌ 错误\n\n未能获取任务ID"
            else:
                error_msg = result.get('message', '未知错误')
                print(f"后端服务响应: {error_msg}")
                return f"## ❌ 后端错误\n\n{error_msg}"
        elif response.status_code == 401:
            print("API需要认证，尝试绕过认证或使用模拟token...")
            
            # 尝试添加一个模拟的认证头部，看是否能绕过认证检查
            headers['Authorization'] = 'Bearer dummy-token-for-testing'
            print("使用模拟token重试...")
            response_retry = requests.post(
                backend_url("/getInitialPoisByPrefs"),
                json=payload,
                headers=headers,
                timeout=30
            )
            
            print(f"重试后响应状态码: {response_retry.status_code}")
            print(f"重试后响应内容: {response_retry.text}")
            
            if response_retry.status_code == 200:
                result = response_retry.json()
                print(f"重试后响应数据: {result}")
                if result.get("success"):
                    rec_id = result.get("recId")
                    if rec_id:
                        # 开始轮询查询结果
                        polling_attempts = 30  # 最多重试30次
                        polling_interval = 5  # 每5秒查询一次
                        
                        print(f"获取到推荐任务ID: {rec_id}")
                        
                        for i in range(polling_attempts):
                            # 查询任务状态
                            status_response = requests.get(
                                backend_url(f"/recommendation-status/{rec_id}"),
                                headers=headers,
                                timeout=10
                            )
                            
                            print(f"轮询状态响应: {status_response.status_code}")
                            print(f"轮询状态内容: {status_response.text}")
                            
                            if status_response.status_code == 200:
                                status_result = status_response.json()
                                print(f"状态查询结果: {status_result}")
                                
                                if status_result.get("success"):
                                    task_status = status_result.get("taskStatus", {})
                                    
                                    if task_status.get("ready"):
                                        if task_status.get("success"):
                                            final_result = task_status.get("data")
                                            print(f"成功获取推荐结果: {final_result}")
                                            # 使用美化函数格式化结果
                                            return format_recommendation_result(final_result)
                                        else:
                                            error_msg = task_status.get("error", "未知错误")
                                            print(f"推荐服务处理失败: {error_msg}")
                                            return f"## ❌ 推荐失败\n\n{error_msg}"
                                    else:
                                        # 任务仍在处理中
                                        remaining_time = (polling_attempts - i - 1) * polling_interval
                                        print(f"任务仍在处理中...剩余时间约 {remaining_time} 秒")
                                        # 继续轮询
                            else:
                                print(f"状态查询失败，HTTP {status_response.status_code}")
                            
                            # 等待一段时间再查询
                            time.sleep(polling_interval)
                        
                        print("处理超时")
                        return f"## ⏱️ 处理超时\n\n### 📋 请求信息\n\n- **活动偏好**: {preference}\n- **出发地点**: {origin}\n- **参与人数**: {people_count} 人\n- **人均预算**: ¥{budget}\n- **最大通勤时间**: {max_transit_time} 分钟\n\n处理时间过长，请稍后再试"
                    else:
                        return f"## ❌ 错误\n\n未能获取任务ID"
                else:
                    error_msg = result.get('message', '未知错误')
                    return f"## ❌ 后端错误\n\n{error_msg}"
            
            return f"## 🔒 认证错误\n\n服务需要认证 (HTTP {response.status_code})"
        elif response.status_code == 404:
            print("API接口不存在，请检查后端路由配置")
            # 尝试另一个可能的API路径
            alt_response = requests.get(backend_url("/"))
            print(f"根路径访问状态: {alt_response.status_code}")
            print(f"根路径响应内容: {alt_response.text}")
            return f"## ❌ API错误\n\nAPI接口未找到 (HTTP 404)，请检查后端配置"
        else:
            print(f"后端服务返回错误状态码: {response.status_code}")
            print(f"后端服务响应内容: {response.text}")
            return f"## ❌ 后端错误\n\nHTTP {response.status_code}\n\n{response.text}"
    
    except requests.exceptions.ConnectionError:
        print("后端服务连接失败")
        return f"## ❌ 连接失败\n\n无法连接到后端服务，请检查服务是否正常运行"
    except requests.exceptions.ReadTimeout:
        print("请求超时")
        return f"## ⏱️ 请求超时\n\n后端服务响应超时，请稍后再试"
    except Exception as e:
        print(f"处理请求异常: {str(e)}")
        return f"## ❌ 系统错误\n\n{str(e)}"


def format_team_activity(activity, index=None):
    """格式化单个团建活动"""
    if not isinstance(activity, dict):
        return f"- {activity}\n"

    title = activity.get("name") or activity.get("title") or "活动"
    time_info = activity.get("time") or activity.get("timeRange") or ""
    address = activity.get("address") or ""
    activity_type = activity.get("type") or ""
    cost = activity.get("cost") or activity.get("perCapitaCost") or ""
    desc = activity.get("description") or ""

    heading = f"### {index}. {title}\n" if index is not None else f"### {title}\n"
    lines = [heading]

    if isinstance(time_info, dict):
        start = time_info.get("start") or time_info.get("from") or ""
        end = time_info.get("end") or time_info.get("to") or ""
        time_info = f"{start}-{end}".strip("-")

    if time_info:
        lines.append(f"- ⏰ 时间: {time_info}\n")
    if address:
        lines.append(f"- 📍 地址: {address}\n")
    if activity_type:
        lines.append(f"- 🏷️ 类型: {activity_type}\n")
    if cost and cost != "暂无":
        lines.append(f"- 💰 人均: {cost}\n")
    if desc:
        lines.append(f"- 📝 说明: {desc}\n")

    travel = activity.get("travel") or {}
    travel_lines = []
    for mode, label in (("driving", "驾车"), ("transit", "公交"), ("walking", "步行")):
        info = None
        if isinstance(travel.get(mode), dict):
            info = travel.get(mode)
        elif isinstance(travel.get("allInfo"), dict) and isinstance(travel["allInfo"].get(mode), dict):
            info = travel["allInfo"].get(mode)
        if info:
            duration = info.get("duration") or info.get("time")
            distance = info.get("distance")
            seg = label
            if duration:
                seg += f" {duration}"
            if distance:
                seg += f" / {distance}"
            travel_lines.append(seg)

    if travel_lines:
        lines.append(f"- 🚗 交通: {' | '.join(travel_lines)}\n")
    else:
        walking = travel.get("walkingDistance") or travel.get("walking")
        driving = travel.get("drivingDistance") or travel.get("driving")
        transit = travel.get("transitDistance") or travel.get("transit")
        legacy = []
        if walking:
            legacy.append(f"步行 {walking}")
        if driving:
            legacy.append(f"驾车 {driving}")
        if transit:
            legacy.append(f"公交 {transit}")
        if legacy:
            lines.append(f"- 🚗 交通: {' | '.join(legacy)}\n")

    return "".join(lines) + "\n"


def format_teamplan_result(result_data):
    """美化团建方案结果显示"""
    if isinstance(result_data, str):
        try:
            result_data = json.loads(result_data)
        except Exception:
            return result_data

    if not isinstance(result_data, dict):
        return str(result_data)

    title = result_data.get("title") or result_data.get("name") or "团建方案"
    formatted = f"# 🎉 团建方案\n\n## {title}\n\n"

    budget_info = result_data.get("budgetInfo") or {}
    if budget_info:
        formatted += "## 💰 预算信息\n\n"
        per_capita = budget_info.get("perCapitaCost") or budget_info.get("totalPerCapitaCost")
        total_budget = budget_info.get("totalBudget")
        hotel_cost = budget_info.get("hotelCost")
        activity_count = budget_info.get("activityCount")
        total_cost = budget_info.get("totalCost")

        if per_capita is not None:
            formatted += f"- 人均预算: ¥{per_capita}\n"
        if total_budget is not None:
            formatted += f"- 总预算: ¥{total_budget}\n"
        if total_cost is not None:
            formatted += f"- 活动总花费(人均): ¥{total_cost}\n"
        if hotel_cost:
            formatted += f"- 酒店均价(人均): ¥{hotel_cost}\n"
        if activity_count:
            formatted += f"- 活动数量: {activity_count}\n"
        formatted += "\n"

    hotel = result_data.get("hotel")
    if hotel:
        formatted += "## 🏨 住宿安排\n\n"
        if hotel.get("name"):
            formatted += f"- 酒店: {hotel.get('name')}\n"
        if hotel.get("address"):
            formatted += f"- 地址: {hotel.get('address')}\n"
        if hotel.get("checkin") or hotel.get("checkout"):
            formatted += f"- 入住/退房: {hotel.get('checkin', '')} / {hotel.get('checkout', '')}\n"
        if hotel.get("cost"):
            formatted += f"- 费用: {hotel.get('cost')}\n"
        if hotel.get("description"):
            formatted += f"- 说明: {hotel.get('description')}\n"
        formatted += "\n"

    if result_data.get("isMultiDay") and result_data.get("days"):
        formatted += "## 🗺️ 行程安排\n\n"
        for day in result_data.get("days", []):
            day_label = day.get("day") or ""
            formatted += f"### 第{day_label}天\n\n"
            activities = day.get("activities") or []
            if not activities:
                formatted += "- 暂无活动\n\n"
                continue
            for idx, activity in enumerate(activities, 1):
                formatted += format_team_activity(activity, idx)
    else:
        activities = result_data.get("activities") or []
        formatted += "## 🗺️ 行程安排\n\n"
        if not activities:
            formatted += "暂无活动安排\n\n"
        else:
            for idx, activity in enumerate(activities, 1):
                formatted += format_team_activity(activity, idx)

    return formatted


def teamplan_demo(
    plan_name,
    people_count,
    budget_min,
    budget_max,
    budget_mode,
    start_date,
    end_date,
    start_time,
    end_time,
    start_location,
    distance_km,
    max_transit_time,
    taxi_time,
    other_notes,
):
    """团建方案生成演示函数"""
    print(
        "接收到团建规划请求:",
        plan_name,
        people_count,
        budget_min,
        budget_max,
        budget_mode,
        start_location,
    )

    global backend_ready, backend_failed

    if backend_failed:
        if not plan_name:
            plan_name = "Team Building Plan"
        try:
            people_count = int(people_count or 1)
        except Exception:
            people_count = 1
        people_count = max(1, people_count)

        today_str = date.today().isoformat()
        start_date = start_date or today_str
        end_date = end_date or start_date
        start_time = start_time or "09:00"
        end_time = end_time or "18:00"

        try:
            budget_min_val = float(budget_min) if budget_min is not None else 0
            budget_max_val = float(budget_max) if budget_max is not None else budget_min_val
        except Exception:
            budget_min_val = 0
            budget_max_val = 0

        if budget_max_val < budget_min_val:
            budget_min_val, budget_max_val = budget_max_val, budget_min_val

        if budget_mode == "\u603b\u9884\u7b97":
            per_min = budget_min_val / people_count if people_count else budget_min_val
            per_max = budget_max_val / people_count if people_count else budget_max_val
        else:
            per_min = budget_min_val
            per_max = budget_max_val

        latitude, longitude = get_location_coordinates(start_location or "")
        fallback_plan = fallback_teamplan(
            plan_name,
            people_count,
            [per_min, per_max],
            start_time,
            end_time,
            start_location,
            latitude,
            longitude,
        )
        return format_teamplan_result(fallback_plan)

    if not backend_ready:
        return "## ⏳ 系统状态\n\n后端服务正在启动中，请稍候再试。"

    if not start_location:
        return "## ⚠️ 参数缺失\n\n请填写出发地点。"

    if not plan_name:
        plan_name = "团建方案"

    try:
        people_count = int(people_count or 1)
    except Exception:
        people_count = 1
    people_count = max(1, people_count)

    today_str = date.today().isoformat()
    start_date = start_date or today_str
    end_date = end_date or start_date
    start_time = start_time or "09:00"
    end_time = end_time or "18:00"

    try:
        budget_min_val = float(budget_min) if budget_min is not None else 0
        budget_max_val = float(budget_max) if budget_max is not None else budget_min_val
    except Exception:
        budget_min_val = 0
        budget_max_val = 0

    if budget_max_val < budget_min_val:
        budget_min_val, budget_max_val = budget_max_val, budget_min_val

    if budget_mode == "总预算":
        per_min = budget_min_val / people_count if people_count else budget_min_val
        per_max = budget_max_val / people_count if people_count else budget_max_val
    else:
        per_min = budget_min_val
        per_max = budget_max_val

    if per_max and per_max != per_min:
        budget_str = f"{int(per_min)}-{int(per_max)}"
    else:
        budget_str = str(int(per_min or per_max or 0))

    latitude, longitude = get_location_coordinates(start_location)
    start_location_coords = f"{longitude},{latitude}"

    payload = {
        "name": plan_name,
        "people": people_count,
        "budget": budget_str,
        "timeRange": {"start": start_time, "end": end_time},
        "dateRange": {"start": start_date, "end": end_date},
        "needAccommodation": start_date != end_date,
        "startLocation": start_location,
        "startLocationCoords": start_location_coords,
        "distance": int(distance_km or 10),
        "maxTransitTime": int(max_transit_time or 60),
        "taxiTime": int(taxi_time or 30),
    }
    if other_notes:
        payload["personalNeeds"] = other_notes

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "User-Agent": "Mozilla/5.0 (compatible; HIPONG App)",
        "Origin": "http://127.0.0.1:13579",
        "Referer": "http://127.0.0.1:13579/",
    }

    try:
        response = requests.post(
            backend_url("/api/plan-teambuilding"),
            json=payload,
            headers=headers,
            timeout=30,
        )

        if response.status_code != 200:
            return f"## ❌ 后端错误\n\nHTTP {response.status_code}\n\n{response.text}"

        result = response.json()
        if not result.get("success") or not result.get("planId"):
            return f"## ❌ 生成失败\n\n{result.get('message', '未知错误')}"

        plan_id = result["planId"]
        polling_attempts = 30
        polling_interval = 5

        for i in range(polling_attempts):
            status_response = requests.get(
                backend_url(f"/api/plan-status/{plan_id}"),
                headers=headers,
                timeout=10,
            )

            if status_response.status_code == 200:
                status_result = status_response.json()
                if status_result.get("success"):
                    if status_result.get("ready"):
                        if status_result.get("planSuccess"):
                            return format_teamplan_result(status_result.get("data"))
                        return f"## ❌ 生成失败\n\n{status_result.get('error', '未知错误')}"
            time.sleep(polling_interval)

        return "## ⏱️ 处理超时\n\n团建方案生成耗时较长，请稍后再试。"

    except requests.exceptions.ConnectionError:
        return "## ❌ 连接失败\n\n无法连接到后端服务，请确认服务是否已启动。"
    except requests.exceptions.ReadTimeout:
        return "## ⏱️ 请求超时\n\n后端服务响应超时，请稍后再试。"
    except Exception as e:
        return f"## ❌ 系统错误\n\n{str(e)}"

# 定义CSS样式，简化版
custom_css = """
    .container {
        max-width: 600px;
        margin: auto;
        padding: 20px;
    }
    .input-group {
        margin: 10px 0;
    }
    .button-row {
        display: flex;
        gap: 10px;
        margin-top: 20px;
    }
"""

# 创建 Gradio 界面 - 添加 Tab 切换
with gr.Blocks(title="HIPONG 智能团建与碰面系统", css=custom_css) as demo:
    gr.Markdown("# HIPONG 智能团建与碰面系统")
    gr.Markdown("在上方切换碰面地点推荐或团建策划")

    with gr.Tabs():
        with gr.Tab("碰面地点推荐"):
            with gr.Column():
                gr.Markdown("**活动偏好**")
                preference = gr.Textbox(placeholder="请用一句话描述您的偏好，例如：美食探索、户外运动")
                gr.Markdown("**目的地类型**")
                types = gr.CheckboxGroup(choices=["餐饮", "体育休闲", "购物", "风景名胜", "科教文化"], value=["餐饮", "体育休闲"])
                gr.Markdown("**出发地点**")
                origin = gr.Textbox(placeholder="例如：杭州市西湖区")
                gr.Markdown("**参与人数**")
                people_count = gr.Slider(1, 20, value=1, step=1)
                gr.Markdown("**人均预算（元）**")
                budget = gr.Number(value=200)
                gr.Markdown("**最大通勤时间（分钟）**")
                max_transit_time = gr.Slider(10, 120, value=60, step=10)

                partner_locations = []
                for i in range(19):
                    partner_locations.append(
                        gr.Textbox(
                            visible=False,
                            label=f"同行者{i+1}出发地点",
                            placeholder="例如：北京市朝阳区",
                        )
                    )

                generate_btn = gr.Button("生成推荐", variant="primary", size="lg")
                output = gr.Markdown(label="推荐结果")

                def update_partner_inputs(count):
                    count = int(count)
                    partner_inputs = []
                    for i in range(19):
                        partner_inputs.append(gr.update(visible=i < count - 1))
                    return partner_inputs

                people_count.change(
                    fn=update_partner_inputs,
                    inputs=[people_count],
                    outputs=partner_locations,
                )

                def process_with_loading(preference, types, origin, people_count, budget, max_transit_time, *partner_locs):
                    yield "## ⏳ 正在处理您的请求...\n\n系统正在为您生成推荐，请稍候..."
                    result = hipong_demo(preference, types, origin, people_count, budget, max_transit_time, *partner_locs)
                    yield result

                generate_btn.click(
                    fn=process_with_loading,
                    inputs=[preference, types, origin, people_count, budget, max_transit_time] + partner_locations,
                    outputs=output,
                )

        with gr.Tab("团建策划"):
            with gr.Column():
                gr.Markdown("**团建计划名称**")
                plan_name = gr.Textbox(placeholder="例如：周末团建·杭州")

                gr.Markdown("**参与人数**")
                team_people = gr.Slider(2, 50, value=10, step=1)

                gr.Markdown("**预算模式**")
                budget_mode = gr.Radio(choices=["人均预算", "总预算"], value="人均预算")

                gr.Markdown("**预算范围（元）**")
                team_budget_min = gr.Number(value=200, label="最低预算")
                team_budget_max = gr.Number(value=400, label="最高预算")

                gr.Markdown("**活动日期**")
                team_start_date = gr.Textbox(value=date.today().isoformat(), label="开始日期 (YYYY-MM-DD)")
                team_end_date = gr.Textbox(value=date.today().isoformat(), label="结束日期 (YYYY-MM-DD)")

                gr.Markdown("**活动时间**")
                team_start_time = gr.Textbox(value="09:00", label="开始时间 (HH:MM)")
                team_end_time = gr.Textbox(value="18:00", label="结束时间 (HH:MM)")

                gr.Markdown("**出发地点**")
                team_start_location = gr.Textbox(placeholder="例如：杭州市西湖区")

                gr.Markdown("**距离范围（公里）**")
                team_distance = gr.Slider(1, 30, value=10, step=1)

                gr.Markdown("**通勤限制**")
                team_max_transit = gr.Slider(10, 120, value=60, step=5, label="公共交通时间（分钟）")
                team_taxi_time = gr.Slider(10, 120, value=30, step=5, label="打车时间（分钟）")

                gr.Markdown("**个性化需求**")
                team_notes = gr.Textbox(lines=3, placeholder="例如：想要户外活动或有蹦床的场地")

                team_generate_btn = gr.Button("生成团建方案", variant="primary", size="lg")
                team_output = gr.Markdown(label="团建方案结果")

                def process_teamplan_with_loading(
                    plan_name,
                    people_count,
                    budget_min,
                    budget_max,
                    budget_mode,
                    start_date,
                    end_date,
                    start_time,
                    end_time,
                    start_location,
                    distance_km,
                    max_transit_time,
                    taxi_time,
                    other_notes,
                ):
                    yield "## ⏳ 正在生成团建方案...\n\n请稍候，系统正在规划活动。"
                    result = teamplan_demo(
                        plan_name,
                        people_count,
                        budget_min,
                        budget_max,
                        budget_mode,
                        start_date,
                        end_date,
                        start_time,
                        end_time,
                        start_location,
                        distance_km,
                        max_transit_time,
                        taxi_time,
                        other_notes,
                    )
                    yield result

                team_generate_btn.click(
                    fn=process_teamplan_with_loading,
                    inputs=[
                        plan_name,
                        team_people,
                        team_budget_min,
                        team_budget_max,
                        budget_mode,
                        team_start_date,
                        team_end_date,
                        team_start_time,
                        team_end_time,
                        team_start_location,
                        team_distance,
                        team_max_transit,
                        team_taxi_time,
                        team_notes,
                    ],
                    outputs=team_output,
                )

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=13579, share=False)
